// utils/latexParser.js
// 将LaTeX公式字符串转换为HTML，用于小程序 rich-text 组件渲染

function parseLatex(latex) {
  if (!latex || typeof latex !== 'string') return '';

  let html = latex
    // 转义HTML特殊字符
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    // 分数 \frac{a}{b} → 使用表格实现上下排列
    .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '<table style="display:inline-table;vertical-align:middle;border-collapse:collapse;margin:0 4px;"><tr><td style="border-bottom:1px solid currentColor;padding-bottom:2px;text-align:center;">$1</td></tr><tr><td style="text-align:center;padding-top:2px;">$2</td></tr></table>')
    // 上标 ^ 和 下标 _
    .replace(/\^\{([^}]+)\}/g, '<sup style="font-size:0.7em;vertical-align:super;">$1</sup>')
    .replace(/\^([a-zA-Z0-9])/g, '<sup style="font-size:0.7em;vertical-align:super;">$1</sup>')
    .replace(/_\{([^}]+)\}/g, '<sub style="font-size:0.7em;vertical-align:sub;">$1</sub>')
    .replace(/_([a-zA-Z0-9])/g, '<sub style="font-size:0.7em;vertical-align:sub;">$1</sub>')
    // 根号 \sqrt{x}
    .replace(/\\sqrt\{([^}]+)\}/g, '<span style="font-size:1.1em;">√</span><span style="border-top:1px solid currentColor;padding-top:2px;">$1</span>')
    .replace(/\\sqrt/g, '√')
    // 希腊字母
    .replace(/\\alpha/g, 'α')
    .replace(/\\beta/g, 'β')
    .replace(/\\gamma/g, 'γ')
    .replace(/\\delta/g, 'δ')
    .replace(/\\Delta/g, 'Δ')
    .replace(/\\epsilon/g, 'ε')
    .replace(/\\varepsilon/g, 'ε')
    .replace(/\\zeta/g, 'ζ')
    .replace(/\\eta/g, 'η')
    .replace(/\\theta/g, 'θ')
    .replace(/\\vartheta/g, 'ϑ')
    .replace(/\\Theta/g, 'Θ')
    .replace(/\\iota/g, 'ι')
    .replace(/\\kappa/g, 'κ')
    .replace(/\\lambda/g, 'λ')
    .replace(/\\Lambda/g, 'Λ')
    .replace(/\\mu/g, 'μ')
    .replace(/\\nu/g, 'ν')
    .replace(/\\xi/g, 'ξ')
    .replace(/\\Xi/g, 'Ξ')
    .replace(/\\pi/g, 'π')
    .replace(/\\Pi/g, 'Π')
    .replace(/\\rho/g, 'ρ')
    .replace(/\\varrho/g, 'ϱ')
    .replace(/\\sigma/g, 'σ')
    .replace(/\\Sigma/g, 'Σ')
    .replace(/\\tau/g, 'τ')
    .replace(/\\upsilon/g, 'υ')
    .replace(/\\phi/g, 'φ')
    .replace(/\\varphi/g, 'φ')
    .replace(/\\Phi/g, 'Φ')
    .replace(/\\chi/g, 'χ')
    .replace(/\\psi/g, 'ψ')
    .replace(/\\Psi/g, 'Ψ')
    .replace(/\\omega/g, 'ω')
    .replace(/\\Omega/g, 'Ω')
    // 数学符号
    .replace(/\\infty/g, '∞')
    .replace(/\\cdot/g, '·')
    .replace(/\\times/g, '×')
    .replace(/\\div/g, '÷')
    .replace(/\\pm/g, '±')
    .replace(/\\mp/g, '∓')
    .replace(/\\neq/g, '≠')
    .replace(/\\approx/g, '≈')
    .replace(/\\sim/g, '∼')
    .replace(/\\propto/g, '∝')
    .replace(/\\rightarrow/g, '→')
    .replace(/\\leftarrow/g, '←')
    .replace(/\\Rightarrow/g, '⇒')
    .replace(/\\Leftarrow/g, '⇐')
    .replace(/\\leftrightarrow/g, '↔')
    .replace(/\\partial/g, '∂')
    .replace(/\\nabla/g, '∇')
    .replace(/\\sum/g, 'Σ')
    .replace(/\\int/g, '∫')
    .replace(/\\prod/g, 'Π')
    .replace(/\\oint/g, '∮')
    .replace(/\\infty/g, '∞')
    .replace(/\\nabla/g, '∇')
    .replace(/\\forall/g, '∀')
    .replace(/\\exists/g, '∃')
    .replace(/\\in/g, '∈')
    .replace(/\\notin/g, '∉')
    .replace(/\\subset/g, '⊂')
    .replace(/\\supset/g, '⊃')
    .replace(/\\subseteq/g, '⊆')
    .replace(/\\supseteq/g, '⊇')
    .replace(/\\cap/g, '∩')
    .replace(/\\cup/g, '∪')
    .replace(/\\emptyset/g, '∅')
    .replace(/\\perp/g, '⊥')
    .replace(/\\parallel/g, '∥')
    .replace(/\\angle/g, '∠')
    .replace(/\\triangle/g, '△')
    .replace(/\\square/g, '□')
    .replace(/\\diamond/g, '◇')
    .replace(/\\star/g, '★')
    .replace(/\\bullet/g, '•')
    .replace(/\\circ/g, '○')
    .replace(/\\bigcirc/g, '○')
    .replace(/\\odot/g, '⊙')
    .replace(/\\oplus/g, '⊕')
    .replace(/\\otimes/g, '⊗')
    .replace(/\\oslash/g, '⊘')
    .replace(/\\leq/g, '≤')
    .replace(/\\geq/g, '≥')
    .replace(/\\ll/g, '≪')
    .replace(/\\gg/g, '≫')
    .replace(/\\equiv/g, '≡')
    .replace(/\\cong/g, '≅')
    .replace(/\\sim/g, '∼')
    .replace(/\\simeq/g, '≃')
    .replace(/\\propto/g, '∝')
    .replace(/\\prec/g, '≺')
    .replace(/\\succ/g, '≻')
    .replace(/\\preceq/g, '≼')
    .replace(/\\succeq/g, '≽')
    .replace(/\\mid/g, '∣')
    .replace(/\\nmid/g, '∤')
    .replace(/\\parallel/g, '∥')
    .replace(/\\nparallel/g, '∦')
    .replace(/\\perp/g, '⊥')
    .replace(/\\not/g, '¬')
    .replace(/\\and/g, '∧')
    .replace(/\\or/g, '∨')
    .replace(/\\Rightarrow/g, '⇒')
    .replace(/\\Leftarrow/g, '⇐')
    .replace(/\\Leftrightarrow/g, '⇔')
    .replace(/\\mapsto/g, '↦')
    .replace(/\\to/g, '→')
    .replace(/\\gets/g, '←')
    // 三角函数
    .replace(/\\sin/g, 'sin')
    .replace(/\\cos/g, 'cos')
    .replace(/\\tan/g, 'tan')
    .replace(/\\cot/g, 'cot')
    .replace(/\\sec/g, 'sec')
    .replace(/\\csc/g, 'csc')
    .replace(/\\arcsin/g, 'arcsin')
    .replace(/\\arccos/g, 'arccos')
    .replace(/\\arctan/g, 'arctan')
    .replace(/\\sinh/g, 'sinh')
    .replace(/\\cosh/g, 'cosh')
    .replace(/\\tanh/g, 'tanh')
    .replace(/\\log/g, 'log')
    .replace(/\\ln/g, 'ln')
    .replace(/\\exp/g, 'exp')
    .replace(/\\lim/g, 'lim')
    .replace(/\\max/g, 'max')
    .replace(/\\min/g, 'min')
    .replace(/\\sup/g, 'sup')
    .replace(/\\inf/g, 'inf')
    .replace(/\\arg/g, 'arg')
    .replace(/\\deg/g, 'deg')
    .replace(/\\det/g, 'det')
    .replace(/\\dim/g, 'dim')
    .replace(/\\gcd/g, 'gcd')
    .replace(/\\hom/g, 'hom')
    .replace(/\\ker/g, 'ker')
    .replace(/\\Pr/g, 'Pr')
    .replace(/\\Re/g, 'Re')
    .replace(/\\Im/g, 'Im')
    // 括号
    .replace(/\\left\(/g, '(')
    .replace(/\\right\)/g, ')')
    .replace(/\\left\[/g, '[')
    .replace(/\\right\]/g, ']')
    .replace(/\\left\\\{/g, '{')
    .replace(/\\right\\\}/g, '}')
    .replace(/\\langle/g, '⟨')
    .replace(/\\rangle/g, '⟩')
    .replace(/\\left\|/g, '|')
    .replace(/\\right\|/g, '|')
    .replace(/\\left\./g, '')
    .replace(/\\right\./g, '')
    .replace(/\\left/g, '')
    .replace(/\\right/g, '')
    // 重音
    .replace(/\\vec\{([^}]+)\}/g, '$1⃗')
    .replace(/\\hat\{([^}]+)\}/g, '$1̂')
    .replace(/\\bar\{([^}]+)\}/g, '$1̄')
    .replace(/\\dot\{([^}]+)\}/g, '$1̇')
    .replace(/\\ddot\{([^}]+)\}/g, '$1̈')
    .replace(/\\tilde\{([^}]+)\}/g, '$1̃')
    .replace(/\\widetilde\{([^}]+)\}/g, '$1̃')
    .replace(/\\acute\{([^}]+)\}/g, '$1́')
    .replace(/\\grave\{([^}]+)\}/g, '$1̀')
    .replace(/\\breve\{([^}]+)\}/g, '$1̆')
    .replace(/\\check\{([^}]+)\}/g, '$1̌')
    .replace(/\\mathring\{([^}]+)\}/g, '$1̊')
    .replace(/\\overline\{([^}]+)\}/g, '<span style="text-decoration:overline;">$1</span>')
    .replace(/\\underline\{([^}]+)\}/g, '<span style="text-decoration:underline;">$1</span>')
    .replace(/\\overbrace\{([^}]+)\}/g, '<span style="border-top:1px solid;">$1</span>')
    .replace(/\\underbrace\{([^}]+)\}/g, '<span style="border-bottom:1px solid;">$1</span>')
    // 粗体
    .replace(/\\mathbf\{([^}]+)\}/g, '<strong>$1</strong>')
    .replace(/\\textbf\{([^}]+)\}/g, '<strong>$1</strong>')
    .replace(/\\textit\{([^}]+)\}/g, '<em>$1</em>')
    .replace(/\\text\{([^}]+)\}/g, '$1')
    .replace(/\\mathrm\{([^}]+)\}/g, '$1')
    // 空格
    .replace(/\\quad/g, '&nbsp;&nbsp;')
    .replace(/\\qquad/g, '&nbsp;&nbsp;&nbsp;&nbsp;')
    .replace(/\\,/g, '&nbsp;')
    .replace(/\\;/g, '&nbsp;&nbsp;')
    .replace(/\\:/g, '&nbsp;')
    .replace(/\\!/g, '')
    .replace(/\\ /g, ' ')
    .replace(/\\\s/g, ' ')
    // 省略号
    .replace(/\\dots/g, '…')
    .replace(/\\cdots/g, '⋯')
    .replace(/\\vdots/g, '⋮')
    .replace(/\\ddots/g, '⋱')
    .replace(/\\ldots/g, '…')
    // 度数
    .replace(/\\degree/g, '°')
    .replace(/\\circ/g, '°')
    // 百分号
    .replace(/\\%/g, '%')
    // 最后去掉剩余的单反斜杠
    .replace(/\\([a-zA-Z]+)/g, '$1')
    .replace(/\\([^a-zA-Z])/g, '$1')
    .replace(/\\/g, '');

  return `<span style="font-family: 'Times New Roman', 'Georgia', 'Cambria Math', 'STIX Two Math', serif; font-style: italic; font-size: 1.05em; color: inherit; line-height: 1.8;">${html}</span>`;
}

module.exports = { parseLatex };
